In [2]:
import pandas as pd
import numpy as np

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'

In [4]:
df = pd.read_csv(url, sep =',')

In [5]:
df.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [8]:
meltdf = pd.melt(df, id_vars = ['country','beer_servings'],value_vars = ['wine_servings','total_litres_of_pure_alcohol','continent'])

In [9]:
meltdf.head(20)

              country  beer_servings       variable value
0         Afghanistan              0  wine_servings     0
1             Albania             89  wine_servings    54
2             Algeria             25  wine_servings    14
3             Andorra            245  wine_servings   312
4              Angola            217  wine_servings    45
5   Antigua & Barbuda            102  wine_servings    45
6           Argentina            193  wine_servings   221
7             Armenia             21  wine_servings    11
8           Australia            261  wine_servings   212
9             Austria            279  wine_servings   191
10         Azerbaijan             21  wine_servings     5
11            Bahamas            122  wine_servings    51
12            Bahrain             42  wine_servings     7
13         Bangladesh              0  wine_servings     0
14           Barbados            143  wine_servings    36
15            Belarus            142  wine_servings    42
16            Belgium            295  wine_servings   212
17             Belize            263  wine_servings     8
18              Benin             34  wine_servings    13
19             Bhutan             23  wine_servings     0

In [13]:
data =  pd.read_csv('data.csv')

In [14]:
data.head()

,Unnamed: 0,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,0,Afghanistan,Southern Asia,153.0,3.575,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,1.95210,2015
1,1,Albania,Central and Eastern Europe,95.0,4.959,0.87867,0.80434,0.81325,0.35733,0.06413,0.14272,1.89894,2015
2,2,Algeria,Middle East and Northern Africa,68.0,5.605,0.93929,1.07772,0.61766,0.28579,0.17383,0.07822,2.43209,2015
3,3,Angola,Sub-Saharan Africa,137.0,4.033,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939,2015
4,4,Argentina,Latin America and Caribbean,30.0,6.574,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2.83600,2015

In [15]:
data.sort_values(['Year', 'Happiness Score'],ascending = [True,False],inplace = True)

In [16]:
data

,Unnamed: 0,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
141,141,Switzerland,Western Europe,1.0,7.587,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2.517380,2015
60,60,Iceland,Western Europe,2.0,7.561,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2.702010,2015
38,38,Denmark,Western Europe,3.0,7.527,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2.492040,2015
108,108,Norway,Western Europe,4.0,7.522,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2.465310,2015
25,25,Canada,North America,5.0,7.427,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2.451760,2015
46,46,Finland,Western Europe,6.0,7.406,1.290250,1.318260,0.889110,0.641690,0.413720,0.233510,2.619550,2015
102,102,Netherlands,Western Europe,7.0,7.378,1.329440,1.280170,0.892840,0.615760,0.318140,0.476100,2.465700,2015
140,140,Sweden,Western Europe,8.0,7.364,1.331710,1.289070,0.910870,0.659800,0.438440,0.362620,2.371190,2015
103,103,New Zealand,Australia and New Zealand,9.0,7.286,1.250180,1.319670,0.908370,0.639380,0.429220,0.475010,2.264250,2015
6,6,Australia,Australia and New Zealand,10.0,7.284,1.333580,1.309230,0.931560,0.651240,0.356370,0.435620,2.266460,2015
66,66,Israel,Middle East and Northern Africa,11.0,7.278,1.228570,1.223930,0.913870,0.413190,0.077850,0.331720,3.088540,2015
34,34,Costa Rica,Latin America and Caribbean,12.0,7.226,0.955780,1.237880,0.860270,0.633760,0.105830,0.254970,3.177280,2015
7,7,Austria,Western Europe,13.0,7.200,1.337230,1.297040,0.890420,0.624330,0.186760,0.330880,2.533200,2015
93,93,Mexico,Latin America and Caribbean,14.0,7.187,1.020540,0.914510,0.814440,0.481810,0.213120,0.140740,3.602140,2015
157,157,United States,North America,15.0,7.119,1.394510,1.247110,0.861790,0.546040,0.158900,0.401050,2.510110,2015
19,19,Brazil,Latin America and Caribbean,16.0,6.983,0.981240,1.232870,0.697020,0.490490,0.175210,0.145740,3.260010,2015
84,84,Luxembourg,Western Europe,17.0,6.946,1.563910,1.219630,0.918940,0.615830,0.377980,0.280340,1.969610,2015
65,65,Ireland,Western Europe,18.0,6.940,1.335960,1.369480,0.895330,0.617770,0.287030,0.459010,1.975700,2015
12,12,Belgium,Western Europe,19.0,6.937,1.307820,1.285660,0.896670,0.584500,0.225400,0.222500,2.414840,2015
155,155,United Arab Emirates,Middle East and Northern Africa,20.0,6.901,1.427270,1.125750,0.809250,0.641570,0.385830,0.264280,2.247430,2015
156,156,United Kingdom,Western Europe,21.0,6.867,1.266370,1.285480,0.909430,0.596250,0.320670,0.519120,1.969940,2015
109,109,Oman,Middle East and Northern Africa,22.0,6.853,1.360110,1.081820,0.762760,0.632740,0.325240,0.215420,2.474890,2015
160,160,Venezuela,Latin America and Caribbean,23.0,6.810,1.044240,1.255960,0.720520,0.429080,0.110690,0.058410,3.191310,2015
127,127,Singapore,Southeastern Asia,24.0,6.798,1.521860,1.020000,1.025250,0.542520,0.492100,0.311050,1.885010,2015
112,112,Panama,Latin America and Caribbean,25.0,6.786,1.063530,1.198500,0.796610,0.542100,0.092700,0.244340,2.848480,2015
50,50,Germany,Western Europe,26.0,6.750,1.327920,1.299370,0.891860,0.614770,0.218430,0.282140,2.115690,2015
28,28,Chile,Latin America and Caribbean,27.0,6.670,1.107150,1.124470,0.858570,0.441320,0.128690,0.333630,2.675850,2015
119,119,Qatar,Middle East and Northern Africa,28.0,6.611,1.690420,1.078600,0.797330,0.640400,0.522080,0.325730,1.556740,2015
47,47,France,Western Europe,29.0,6.575,1.277780,1.260380,0.945790,0.550110,0.206460,0.123320,2.211260,2015
4,4,Argentina,Latin America and Caribbean,30.0,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,417,Malawi,Sub-Saharan Africa,136.0,3.970,0.233442,0.512569,0.315090,0.466915,0.072712,0.287170,2.081786,2017
357,357,Chad,Sub-Saharan Africa,137.0,3.936,0.438013,0.953856,0.041135,0.162342,0.053582,0.216114,2.071238,2017
494,494,Zimbabwe,Sub-Saharan Africa,138.0,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017
410,410,Lesotho,Sub-Saharan Africa,139.0,3.808,0.521021,1.190095,0.000000,0.390661,0.119095,0.157497,1.429835,2017
333,333,Angola,Sub-Saharan Africa,140.0,3.795,0.858428,1.104412,0.049869,0.000000,0.069720,0.097926,1.614482,2017
330,330,Afghanistan,Southern Asia,141.0,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2.150801,2017
348,348,Botswana,Sub-Saharan Africa,142.0,3.766,1.122094,1.221555,0.341756,0.505196,0.098583,0.099348,0.377914,2017
344,344,Benin,Sub-Saharan Africa,143.0,3.657,0.431085,0.435300,0.209930,0.425963,0.060929,0.207948,1.885631,2017
416,416,Madagascar,Sub-Saharan Africa,144.0,3.644,0.305809,0.913020,0.375223,0.189197,0.067232,0.208733,1.584613,2017
385,385,Haiti,Latin America and Caribbean,145.0,3.603,0.368610,0.640450,0.277321,0.030370,0.099872,0.489204,1.697168,2017
492,492,Yemen,Middle East and Northern Africa,146.0,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017
464,464,South Sudan,Sub-Saharan Africa,147.0,3.591,0.397249,0.601323,0.163486,0.147062,0.116794,0.285671,1.879567,2017
411,411,Liberia,Sub-Saharan Africa,148.0,3.533,0.119042,0.872118,0.229918,0.332881,0.038948,0.266550,1.673286,2017
384,384,Guinea,Sub-Saharan Africa,149.0,3.507,0.244550,0.791245,0.194129,0.348588,0.110938,0.264815,1.552312,2017
478,478,Togo,Sub-Saharan Africa,150.0,3.495,0.305445,0.431883,0.247106,0.380426,0.095665,0.196896,1.837229,2017
452,452,Rwanda,Sub-Saharan Africa,151.0,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061,2017
472,472,Syria,Middle East and Northern Africa,152.0,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574,2017
476,476,Tanzania,Sub-Saharan Africa,153.0,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130,2017
352,352,Burundi,Sub-Saharan Africa,154.0,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024,2017
356,356,Central African Republic,Sub-Saharan Africa,155.0,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005,2017
361,361,Comoros,Sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
369,369,Djibouti,Sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
387,387,Hong Kong,Eastern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
407,407,Laos,Southeastern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
439,439,Oman,Middle East and Northern Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
448,448,Puerto Rico,Latin America and Caribbean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
461,461,Somaliland Region,Sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
468,468,Suriname,Latin America and Caribbean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
469,469,Swaziland,Sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
473,473,Taiwan,Eastern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017

In [17]:
data.isnull().any().any()

True